### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Bhavitratechsolutions**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by Bhavitratechsolutions** [comment]
I have learned a new thing today from github, I already implemented this technique to my hosting site-[https://www.bhavitrahostbd.com/](https://www.bhavitrahostbd.com/)

**Comment by jamuhl** [comment]
What is this sample project? Looks just like a website - is it Open Source so others can learn from it? Is it using locize or just i18next?

**Comment by Bhavitratechsolutions** [comment]
bhavitrahostbd.com where we use i18next plugin for language translation,
thanks for i18next

**Comment by jamuhl** [comment]
So, this is basically just a company using i18next. We do not add such links...sorry. Tutorials, Boilerplates, ok...just uplink to some commercial product...nope, not adding as it does not add values for other devs

**Comment by Bhavitratechsolutions** [comment]
Ok, I got it
Thanks have a nice day

**Pull request closed without merging**
